apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ include "kiss-eck.name" . }}
  labels:
  {{- include "kiss-eck.labels" . | nindent 4 }}
spec:
  config:
    server.publicBaseUrl: https://{{ .Values.kibanaDomain }}
  count: 1
  elasticsearchRef:
    name: kiss
  enterpriseSearchRef:
    name: kiss
  podTemplate:
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: kibana-data
        persistentVolumeClaim:
          claimName: {{ include "kiss-eck.name" . }}-kibana-data
  volumeClaimTemplates:
  - metadata:
      name: kibana-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.storage.kibana.size }}
      {{- if .Values.storage.storageClassName }}
      storageClassName: {{ .Values.storage.storageClassName }}
      {{- end }}
  version: {{ .Values.elasticVersion }}
